name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
resources:
- repo: self
  fetchDepth: 1
steps:
- task: PowerShell@2
  displayName: 'Download LoggingCommandFunctions.ps1'
  inputs:
    targetType: 'filePath'
    filePath: ./Azure-DevOps-Pipelines/download-LoggingCommandFunctions.ps1
    arguments: '-Verbose'
- template: sync-template.yml
  parameters:
    repositories:
    - https://github.com/thnetii/dotnet-common.git
    - https://github.com/thnetii/azure-msbuild.git
- script: "git clean -ffdx"
  condition: true
  displayName: "Cleaning repository"
  continueOnError: true
